// CAPEITEM_FW_MARTLOCK

export const capes = [
  "CAPEITEM_FW_MARTLOCK",
  "CAPEITEM_FW_FORTSTERLING",
  "CAPEITEM_FW_LYMHURST",
  "CAPEITEM_FW_CAERLEON",
  "CAPEITEM_FW_BRIDGEWATCH",
  "CAPEITEM_FW_THETFORD",
  "CAPEITEM_UNDEAD",
  "CAPEITEM_KEEPER",
  "CAPEITEM_MORGANA",
];
